#define BUILD_COMMIT_ID "613cf98-dirty"
#define PROJECT_VERSION "1.0.0"
#define PROJECT_VERSION_BUILD_NO "1"
#define PROJECT_VERSION_LONG PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO " (" BUILD_COMMIT_ID ")"
